routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OfficeController;
use App\Http\Controllers\GamesController;

Route::get('/', function () {
    return view('welcome');
});

Route::get('/floppy', [GamesController::class, 'floppy'])->name('floppy');
Route::get('/solitaire', [GamesController::class, 'solitaire'])->name('solitaire');
Route::get('/chess', [GamesController::class, 'chess'])->name('chess');
Route::get('/shooter', [GamesController::class, 'shooter'])->name('shooter');



Route::get('/platformer', function () {
    return view('games.platformer.platformer');
});

Route::get('/office_save_to_txt', [OfficeController::class,'save_to_txt']);


Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Tags\HasTags;

class Article extends Model
{
    use HasFactory;
    use HasTags;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'content', 'publish'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'author',
        'cover',
        'file',
        'rating'
    ];

    public function coverPath()
    {
        return '/storage/' . $this->cover;
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];

    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ArticleController extends Controller
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ExcelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use SimpleXLS;

class ExcelController extends Controller
{
    public function parse_rows($file)
    {
        return new SimpleXLS($file);
    }
}

app/Http/Controllers/GamesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class GamesController extends Controller
{
    public function floppy()
    {
        return view('games.floppy.floppy');
    }

    public function solitaire()
    {
        return view('games.solitaire.solitaire');
    }

    public function chess()
    {
        return view('games.chess.chess');
    }

    public function shooter()
    {
        return view('games.shooter.shooter');
    }
}

app/Http/Controllers/OfficeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Storage;

class OfficeController extends Controller
{
    public function save_to_txt()
    {
        $users = User::all();

        foreach ($users as $user) {
            dump($user);
        }

//        Storage::put('users.csv', $users);
    }
}

app/Http/Controllers/SpiderController.php
<?php

namespace App\Http\Controllers;

use Symfony\Component\DomCrawler\Crawler;
use Illuminate\Support\Facades\Storage;

class SpiderController extends Controller
{
    public function sign_in()
    {
        $link = 'https://codecourse.com/api/auth/login';
        $login = 'tikken23@gmail.com';
        $pass = 'ZAGeF@HrdAN@z4u';
        $crawler = $this->create_crawler($link);
    }
    public function parse($link, $jsonToSave)
    {
        $crawler = $this->create_crawler($link);
        $links = $this->get_all_links($crawler);
        $json = $this->create_json($jsonToSave, $links);

        return $json;
    }

    /**
     * @param $link
     */
    public function create_crawler($link)
    {
        $html = file_get_contents($link);
        $crawler = new Crawler(null, $link);
        $crawler->addHtmlContent($html, 'UTF-8');

        return $crawler;
    }

    public function get_all_images($crawler)
    {
        $images = $crawler->filter('img')->each(function($node) {
            $src = $node->attr('src');

            return compact('src');
        });

        return $images;
    }
    /**
     * Symfony dom crawler
     * @param $crawler
     */
    public function get_all_links($crawler)
    {
        $links = $crawler->filter('a')->each(function($node) {
            $href  = $node->attr('href');
            $title = $node->text();

            return compact('href', 'title');
        });

        return $links;
    }

    public function get_all_iframes($crawler)
    {
        $frames = $crawler->filter('iframe')->each(function($node) {
            $src  = $node->attr('src');

            return compact( 'src');
        });

        return $frames[0]['src'];
    }

    /**
     * Obj should be result of get_all_links func
     * @param $filename
     * @param $obj
     */
    public function create_json($filename, $obj)
    {
        $safeObj = json_decode(json_encode($obj));

        if(Storage::disk('local')->has($filename)) {
            Storage::get($filename);
        }

        Storage::disk('local')->put($filename, json_encode($safeObj));

        return Storage::get($filename);
    }
}

app/Http/Livewire/Articles.php
<?php

namespace App\Http\Livewire;

use App\Models\Article;
use Livewire\Component;

class Articles extends Component
{
    public function render()
    {
        $articles = Article::all();

        return view('livewire.articles', ['articles' => $articles]);
    }
}

app/Http/Livewire/Tags.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Spatie\Tags\Tag;

class Tags extends Component
{
    public function render()
    {
        $tags = Tag::all();
        return view('livewire.tags', ['tags' => $tags]);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <h1>dashboard maine</h1>
@endsection

resources/views/games/cards/cards.blade.php
<div class="felt" style="background:url(felt.jpg);">
    <canvas id="game" style=""></canvas>
</div>
<div id="login" class="modal">
    <!-- Modal content -->
    <div class="modal-content">
        <h3>Login</h3>
        <span class="close">&times;</span>
        <form id="loginForm">
            <div id="nameRow" class="row" style="display:none;">
                <div class="col-25"><label for="nname">Name</label></div>
                <div class="col-75"><input id="nname" name="name" type="text" ></div>
            </div>
            <div class="row">
                <div class="col-25"><label for="ename">Email</label></div>
                <div class="col-75"><input id="ename" name="email" type="email" ></div>
            </div>
            <div id="passwordRow" class="row">
                <div class="col-25"><label for="pname">Password</label></div>
                <div class="col-75"><input id="pname" name="pwd" type="password" ></div>
            </div>
            <div id="loginRow" class="row">
                Not a member? register <a href="#none" onclick="game.showRegister()">here</a><br>
                <button onclick="game.login()">Login</button>
            </div>
            <div id="registerRow" class="row" style="display:none;">
                Already a member? login <a href="#none" onclick="game.showLogin()">here</a>
                <button onclick="game.register()">Register</button>
            </div>
        </form>
    </div>
</div>

resources/views/games/floppy/floppy.blade.php
@extends('layouts.app')

@section('content')
    <div class="tm-sidebar-left">
        <livewire:tags/>
    </div>
    <div class="tm-main uk-width-1-1">
        <div id="floppy" class="floppy uk-padding uk-shadow bg-white uk-margin-medium-bottom"></div>
    </div>
@endsection

resources/views/games/platformer/platformer.blade.php
@extends('layouts.app')

@section('content')
    <div id="platformer" class="platformer uk-padding uk-shadow bg-white uk-margin-medium-bottom"></div>
@endsection

resources/views/games/shooter/shooter.blade.php
{{--@extends('layouts.app')--}}
{{--@section('content')--}}
<script src="/vendor/games/shooter/jquery-2.0.0.min.js" type="text/javascript"></script>
<script src="/vendor/games/shooter/kinetic-v4.5.1.min.js" type="text/javascript"></script>
<script src="/vendor/games/shooter/bootstrap.min.js" type="text/javascript"></script>

<link rel="stylesheet" href="/css/games/shooter/normalize.css"/>
<link rel="stylesheet" href="/css/games/shooter/bootstrap.min.css">
<link rel="stylesheet" href="/css/games/shooter/style.css"/>

<div id="the-navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-inner">
        <div class="pull-left">
            <a class="brand" href="#">2D Shooter</a>
            <ul class="nav">
                <li class="divider-vertical"></li>
                <li><a href="#game-menu" data-toggle="modal">Menu</a></li>
                <li><a href="#settings" data-toggle="modal">Settings</a></li>
                <li><a href="#users" data-toggle="modal">Users</a></li>
                <li><a href="#about" data-toggle="modal">About</a></li>
            </ul>
        </div>
        <div class="pull-right">
            <ul class="nav">
                <li class="divider-vertical"></li>
                <li><a id="game-play" href="#"><i class="icon-play icon-white"></i> Play</a></li>
                <li><a id="game-pause" href="#"><i class="icon-pause icon-white"></i> Pause</a></li>
            </ul>
        </div>
    </div>
</div>

<div id="playground" tabindex="0" role="main"></div>

<div id="game-menu" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2>Game menu</h2>
    </div>
    <div class="modal-body">
        <p id="message-user"></p>
        <p id="message-score"></p>
    </div>
    <div class="modal-footer">
        <button id="game-end" class="btn" data-dismiss="modal">End current game</button>
        <button id="game-begin" class="btn btn-primary" data-dismiss="modal">Begin new game</button>
    </div>
</div>

<div id="settings" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2>Game settings</h2>
    </div>
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="control-group">
                <label class="control-label" for="player-speed">Player speed</label>
                <div class="controls">
                    <input id="player-speed" type="number" value="4" required min="1" pattern="^\d+$"/>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="difficulty">Game difficulty</label>
                <div class="controls">
                    <input id="difficulty" type="number" value="1" required min="1" pattern="^\d+$"/>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn" data-dismiss="modal">Close</button>
        <button id="settings-save" class="btn btn-primary" data-dismiss="modal">Save</button>
    </div>
</div>

<div id="users" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2>User management</h2>
    </div>
    <div class="modal-body">
        <ul class="nav nav-tabs">
            <li class="active"><a href="#all-users" data-toggle="tab">All users</a></li>
            <li><a href="#new-user" data-toggle="tab">New user</a></li>
        </ul>
        <div class="tab-content">
            <div id="all-users" class="tab-pane active">
                <h4>Overview of all user accounts</h4>
                <p>You can log-in as any user to play the game and to improve high scores.</p>
                <div class="content"></div>
            </div>
            <div id="new-user" class="tab-pane">
                <form class="form-horizontal">
                    <fieldset>
                        <legend>Create new user account</legend>
                        <div class="control-group">
                            <label class="control-label" for="new-user-name">Name</label>
                            <div class="controls">
                                <input id="new-user-name" type="text" required pattern="^\S.*\S$|\S" title="username"/>
                                <span class="help-inline hide">new uses was successfully created</span>
                            </div>
                        </div>
                    </fieldset>
                    <div class="form-actions">
                        <input class="btn btn-primary" type="submit" value="Create"/>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div id="about" class="modal hide fade" tabindex="-1" role="dialog">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h2>About 2D Shooter game</h2>
    </div>
    <div class="modal-body">
        <p>2D action-shooter game, client-side JavaScript application with HTML5 and CSS3.</p>
        <p>For more see <a href="https://github.com/mudrutom/2D-Shooter">GitHub repository</a>.</p>
        <h5>How to play:</h5>
        <p>
            Use <code>W</code>,<code>S</code>,<code>A</code>,<code>D</code> keys to move the player
            and mouse-clicks for shooting. The goal of the game is to survive as long as possible.
        </p>
    </div>
</div>

<!-- load main JavaScript using Require.js -->
<script data-main="vendor/games/shooter/game/main.js" src="/vendor/games/shooter/require-2.1.6.min.js" type="text/javascript"></script>
{{--@endsection--}}

resources/views/games/solitaire/solitaire.blade.php
@extends('layouts.app')
@section('content')
    <div class="felt" style="background:url(felt.jpg);">
        <canvas id="game" style=""></canvas>
    </div>
    <div id="login" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
            <h3>Login</h3>
            <span class="close">&times;</span>

{{--            <form id="loginForm">--}}
{{--                <div id="nameRow" class="row" style="display:none;">--}}
{{--                    <div class="col-25"><label for="nname">Name</label></div>--}}
{{--                    <div class="col-75"><input id="nname" name="name" type="text" ></div>--}}
{{--                </div>--}}
{{--                <div class="row">--}}
{{--                    <div class="col-25"><label for="ename">Email</label></div>--}}
{{--                    <div class="col-75"><input id="ename" name="email" type="email" ></div>--}}
{{--                </div>--}}
{{--                <div id="passwordRow" class="row">--}}
{{--                    <div class="col-25"><label for="pname">Password</label></div>--}}
{{--                    <div class="col-75"><input id="pname" name="pwd" type="password" ></div>--}}
{{--                </div>--}}
{{--                <div id="loginRow" class="row">--}}
{{--                    Not a member? register <a href="#none" onclick="game.showRegister()">here</a><br>--}}
{{--                    <button onclick="game.login()">Login</button>--}}
{{--                </div>--}}
{{--                <div id="registerRow" class="row" style="display:none;">--}}
{{--                    Already a member? login <a href="#none" onclick="game.showLogin()">here</a>--}}
{{--                    <button onclick="game.register()">Register</button>--}}
{{--                </div>--}}
{{--            </form>--}}


        </div>
    </div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'JSUX.fun') }}</title>

    <link rel="preload" href="/fonts/Montserrat-Medium.ttf" as="font" type="font/ttf" crossorigin>
    <link rel="preload" href="/fonts/Montserrat-Regular.ttf" as="font" type="font/ttf" crossorigin>
    <link rel="preload" href="/fonts/Montserrat-semibold.ttf" as="font" type="font/ttf" crossorigin>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.6.16/dist/css/uikit.min.css"/>
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.16/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.16/dist/js/uikit-icons.min.js"></script>

    <script src="{{ asset('js/app.js') }}" defer></script>

    @livewireStyles
    @livewireScripts
</head>
<body>
    <div id="app">
        @include('components.navbar.navbar')

        <main class="uk-container uk-flex uk-flex-center uk-margin-bottom">
            @yield('content')
        </main>

    </div>
</body>
</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/livewire/articles.blade.php
<h2 class="uk-heading uk-margin">
    Articles
</h2>

@foreach($articles as $article)
   @include('components.article.article_listItem', ['article' => $article])
@endforeach

resources/views/livewire/tags.blade.php
<div class="uk-card uk-card-default uk-width-1-1" data-sticky-block>
    <h3 class="uk-card-title mb20">Popular tags</h3>

    @foreach($tags as $tag)
        <div class="uk-label uk-margin-small-bottom">
            <span uk-icon="hashtag"></span>
            <span>{{ $tag->name }}</span>
        </div>
    @endforeach
</div>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>